### ISSUE TITLE
Is this project stable?

### ISSUE THREAD

**Issue by callumacrae** [jstuckey/gulp-gzip#11]
The current version of this project is 0.0.8, which under semantic versioning means that it isn't suitable for use in production. Is that true, though? If not, could you bump it to 1.0.0? Cheers!

**Comment by jstuckey** [comment]
Yeah, it's stable and therefore should be 1.0.0. I'll update the version when I get home tonight. 

I was following a trend among npm modules to only use patch versions. Perhaps that was inspired by Node's reluctance to go 1.0. Anyway, it's not semantic, so I'll change it.

**Comment by jstuckey** [comment]
Bumped to 1.0.0. Thanks for bringing this to my attention!

**Comment by callumacrae** [comment]
![](http://media.giphy.com/media/770HJBzDQHyG4/giphy.gif)

thanks :smile:
