### ISSUE TITLE
Bump version number after changed dependencies

### ISSUE THREAD

**Issue by Frank3K** [jstuckey/gulp-gzip#29]
In 6b65f408a0f57d3f87cef86e8c65a29ed25bf97b the `gulp-util` dependency has been removed. Since the version number of `gulp-gzip` has not been changed afterwards, `npm` (or `yarn`) does not "see" the change.

Could you please update the version number and publish the updated version to npm?

**Comment by jstuckey** [comment]
Yes, I will publish tonight. I've been on vacation and unable to publish.

**Comment by jstuckey** [comment]
Published as version 1.4.1.
